name: record
description: Audio recorder from microphone to a given file path with multiple codecs, bit rate and sampling rate options.
version: 5.0.1
publish_to: none
homepage: https://github.com/llfbandit/record/tree/master/record

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.1"

dependencies:
  flutter:
    sdk: flutter

  uuid: ">=3.0.7 <5.0.0"

  record_platform_interface:
    git: https://github.com/kumsumit/record_platform_interface.git
  record_web: 
    git: https://github.com/kumsumit/record_web.git
  record_windows: 
    git: https://github.com/kumsumit/record_windows.git
  record_linux:
    git: https://github.com/kumsumit/record_linux.git
  record_android:
    git: https://github.com/kumsumit/record_android.git
  record_darwin:
    git: https://github.com/kumsumit/record_darwin.git

dev_dependencies:
  # https://pub.dev/packages/flutter_lints
  flutter_lints:
    git: https://github.com/kumsumit/flutter_lints.git
    

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        default_package: record_android
      ios:
        default_package: record_darwin
      web:
        default_package: record_web
      windows:
        default_package: record_windows
      macos:
        default_package: record_darwin
      linux:
        default_package: record_linux
